# Generated by Django 5.0.4 on 2024-04-16 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
