# Generated by Django 5.0.4 on 2024-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sydney', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
